version: '3.8'

services:
  postgres-db:
    image: postgres:16-alpine
    container_name: lms-postgres-container
    environment:
      POSTGRES_USER: lms_user
      POSTGRES_PASSWORD: lms_password
      POSTGRES_MULTIPLE_DATABASES: "lms_db,keycloak_db"
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-multiple-databases.sh:/docker-entrypoint-initdb.d/init-multiple-databases.sh
    networks:
      - lms-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aidoha -d lms_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: lms-keycloak-container
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-db:5432/keycloak_db
      KC_DB_USERNAME: lms_user
      KC_DB_PASSWORD: lms_password

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080" # Открываем Keycloak на порту 8081 компьютера, чтобы не путать с Spring Boot (8080)
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - lms-network

  lms-app:
    image: aidyn055/bitintern-app:latest
    container_name: lms-app-container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/lms_db
      SPRING_DATASOURCE_USERNAME: lms_user
      SPRING_DATASOURCE_PASSWORD: lms_password
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - lms-network

networks:
  lms-network:
    driver: bridge

volumes:
  pgdata:
    driver: local